ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 79929485
  object_id: effb7d90-3c58-431d-5f76-54c01a89cda3
  sha: sha256:b7790cf19d58e738ff2d68760a7f9da84dc2d889af1f9d5cdf14727b9e456055
gitlab-runner-linux-amd64:
  size: 95696417
  object_id: 6ea62fc1-a453-4929-51dc-0ffbdddf4f89
  sha: sha256:4126cf8ca8db0c1e3e675a3039694c6d7ccd0aeb4cd1c34557ff8652bd173883
