ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 82034378
  object_id: 1be8479a-683f-48db-7d79-80e96b59165f
  sha: sha256:4422c550a6583fedfa790e00e7d51c1ee494e5c3f2dffc0a74145417fb9a7a6f
gitlab-runner-linux-amd64:
  size: 95696531
  object_id: a97e84fa-96bb-4c41-4ade-f3b0f3b78b52
  sha: sha256:4e93cf18b68df62ad962014db95773f177920f8daf3a2e7a35a79465b8df2ca4
