ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 82034131
  object_id: 915a08c8-07b0-4498-78a2-8a6c447a23af
  sha: sha256:45ed5baed5171f0169b48266d9015107cee1a8639868a2481ec17a9b0c961c2e
gitlab-runner-linux-amd64:
  size: 107598157
  object_id: 4fce4e71-c310-45fb-6a46-977263b7b4a1
  sha: sha256:ca19f22319c82b7d01ce63515614f4aefe0ae975fe79762dd668f38334801058
