ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 84236913
  object_id: 175e13d9-0586-40cb-7e3e-8cfcebf49979
  sha: sha256:1beacd5cebec16bf857d557d3ce3e7e20fc692639cd36e0cfb3877def06b1e7c
gitlab-runner-linux-amd64:
  size: 107817362
  object_id: 254f786a-53db-419f-514a-6db895f1a502
  sha: sha256:1588776c9b2f342692077176dc2d581a78457eb268e247fa06f9176b4dfd9cfb
