ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 82034378
  object_id: 1be8479a-683f-48db-7d79-80e96b59165f
  sha: sha256:4422c550a6583fedfa790e00e7d51c1ee494e5c3f2dffc0a74145417fb9a7a6f
gitlab-runner-linux-amd64:
  size: 95699560
  object_id: 2b836a52-5178-44d9-4cfc-ba98c19934c2
  sha: sha256:dc6973a8b7a088a72bc3717c28e65731a4f9acc3e6b255ead25b1af4ffe3aff7
