ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 82034257
  object_id: 4241b0cb-2a11-4ced-7f5f-f8299d6654f4
  sha: sha256:c019c608ba2bb009dd673f3230e4d743f36a78d36166c6c2444c05d0aa9ff0d9
gitlab-runner-linux-amd64:
  size: 107594016
  object_id: 99d11c5b-bd12-49fc-591b-5f64f53e72ba
  sha: sha256:df914de244205fceead844eae291c67f1fa69af707403caa8a8e6f160475af43
