ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 79925299
  object_id: e39b3785-865a-43b1-5be6-58dc7e69ae75
  sha: sha256:079e491e942e7a7a090c593db7eb63f3d657b5ca166c38dab59678b165b91eca
gitlab-runner-linux-amd64:
  size: 95696309
  object_id: 33017916-f4b6-4cbc-5058-923ed32b2ef8
  sha: sha256:cd6f470fd3f84f78eac2e7576fca0b2c14fc91a39b3dcecda8f43c55bd549640
