ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 79929485
  object_id: effb7d90-3c58-431d-5f76-54c01a89cda3
  sha: sha256:b7790cf19d58e738ff2d68760a7f9da84dc2d889af1f9d5cdf14727b9e456055
gitlab-runner-linux-amd64:
  size: 95696309
  object_id: 53139473-1cd2-4d96-7cc2-1e7a5010e699
  sha: sha256:4acef3399fb017d65f0f8e04f374d050bdcc5f7f3c133d753502291517760817
