ctop:
  size: 13606047
  object_id: 95624bf2-17fb-4fe1-593f-33acbefa669b
  sha: sha256:b78374734ebe3d14b6edee3d5512c911c250d7fa7f3f964cb00acd3bc5a02a09
docker.tgz:
  size: 81996386
  object_id: a766d935-57f1-41db-6981-9ab59d47bed7
  sha: sha256:882bb03f3fd36ad565b1362f5bbb5d5af5f2410a5c10cae3f9d3d54e2540adc2
gitlab-runner-linux-amd64:
  size: 107817362
  object_id: 254f786a-53db-419f-514a-6db895f1a502
  sha: sha256:1588776c9b2f342692077176dc2d581a78457eb268e247fa06f9176b4dfd9cfb
